name: unit_tests

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:26

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: |
        PYTHONPATH=. pytest-3 -v --tb=short tests/
